{% set name = "construct" %}
{% set version = "2.9.50" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8902fa3abe7e654a0caa14365d8a6331b84e6862f0eb9644e319da9292f1584f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - construct
    - construct.lib

about:
  home: http://construct.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A powerful declarative symmetric parser/builder for binary data

extra:
  recipe-maintainers:
    - DominicAntonacci
