{% set name = "construct" %}
{% set version = "2.10.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08573d1573827a6fe6b846756d54270650e221a6cec6a72e06b582cde775599e

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - construct
    - construct.lib

about:
  home: http://construct.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A powerful declarative symmetric parser/builder for binary data

extra:
  recipe-maintainers:
    - DominicAntonacci
    - kevinheavey
